#--------------------------------------------------------------------------------------------------#
# File:    .gitlab-ci.yml
# Author:  Kelly Thompson <kgt@lanl.gov>
# Date:    Saturday, Nov 13, 2021, 21:09 pm
# Purpose: Instructions for gitlab CI testing.  This script wil be run to test pull requests
# Note:    Copyright (C) 2021 Triad National Security, LLC.  All rights reserved.
#--------------------------------------------------------------------------------------------------#

variables:
  PROJECT: Draco

stages:
  - fasttest
  - test
  - slowtest
  - optional
  - Deploy

include:
  - local: /.gitlab/ci/ccscs-jobs.yml
  - local: /.gitlab/ci/darwin-jobs.yml
  - local: /.gitlab/ci/superlinter.yml
  - local: /.gitlab/ci/msvc-jobs.yml

#--------------------------------------------------------------------------------------------------#
# End .gitlab-ci.yml
#--------------------------------------------------------------------------------------------------#
