#--------------------------------------------------------------------------------------------------#
# File:   .travis.yml
# Author: Kelly Thompson <kgt@lanl.gov>
# Date:   Friday, Jul 13, 2018, 07:41 am
# Purpose: Instructions for Travis continuous integration testing on GitHub.  This script wil be run
#         to test pull requests
# Note:   Copyright (C) 2018-2020 Triad National Security, LLC., All rights reserved.
#--------------------------------------------------------------------------------------------------#

language: cpp
sudo: required
services:
  - docker

#--------------------------------------------------------------------------------------------------#
# Notes: Build docker container before running this script:
#
# 1. cd to directory contataining Dockerfile.
# 2. Build the docker container.  This can take an hour or more.  If you are starting from scratch,
#    you will need to change the first line of the Dockerfile so that it starts from 'ubuntu'
#    instead of 'draco-travis-ci'
#
#    docker build --rm --pull --tag draco-travis-ci:latest .
#
# 3. Commit and upload the updated container. See more detailed notes in tools/Dockerfile.
#--------------------------------------------------------------------------------------------------#

#--------------------------------------------------------------------------------------------------#
# Travis Environment:
#
# HOME=/home/travis
# PWD=/home/travis/build/lanl/Draco
#     (starting directory for Travis, sources are here)
#
# Docker Environment:
#
# - The docker image mounts the PR sources (/home/travis/build/lanl/Draco) as /home/travis/Draco
# - The vendors are at /vendors/spack
# - Spack is already in the environment
#--------------------------------------------------------------------------------------------------#

#branches:
#  only:
#  - master

# stages:
#   - name: style
#     if: type = pull_request
#   - name: test

# jobs:
#   fast_finish: true
#   include::
#     - stage: style
#       env: STYLE=ON DOCKER_TAG=style-checks
#       compiler: gcc
#     - stage: test
#       env: WERROR=ON COVERAGE=ON DRACO_C4=SCALAR DOCKER_TAG=spack-gcc
#       compiler: gcc
#     - stage: test
#       env: WERROR=ON COVERAGE=ON DRACO_C4=MPI DOCKER_TAG=spack-gcc
#       compiler: gcc
#     - stage: test
#       env: WERROR=ON DRACO_C4=MPI AUTODOC=ON DOCKER_TAG=autdoc
#       compiler: gcc

# compiler:
#   - gcc
#   - clang

env:
  global:
    - BUILD_DIR=/home/travis/Draco/build
    - SOURCE_DIR=/home/travis/Draco
    - T_SOURCE_DIR=/home/travis/build/lanl/Draco
    - VENDOR_DIR=/vendors
  matrix:
  - STYLE=ON DOCKER_TAG=style-checks
  - WERROR=ON COVERAGE=ON DRACO_C4=SCALAR DOCKER_TAG=spack-gcc
  - WERROR=ON COVERAGE=ON DRACO_C4=MPI DOCKER_TAG=spack-gcc
  - WERROR=ON DRACO_C4=MPI AUTODOC=ON DOCKER_TAG=autodoc

# matrix:
#   allow_failures:
#     - compiler: gcc
#       env: DISTRO=ubuntu DRACO_C4=SCALAR WERROR=yes
#     - compiler: gcc
#       env: DISTRO=ubuntu STYLE=ON

# Coverage with Docker - https://docs.codecov.io/docs/testing-with-docker

#before_install:
#  - pip install --upgrade --user pip
#  - if [[ ${COVERAGE}  ]]; then pip install --user codecov; fi

#install:
#  - travis_retry timeout 540 docker pull kinetictheory/draco-ci-2020may:${DOCKER_TAG}

jobs:
  fast_finish: true

script:
  - travis_retry timeout 540 docker pull kinetictheory/draco-ci-2020nov:${DOCKER_TAG}
  - if [[ ${COVERAGE:-OFF} == "ON" ]]; then ci_env=`/bin/bash <(curl -s https://codecov.io/env)`; fi
  - docker run ${ci_env} -v ${T_SOURCE_DIR}:${SOURCE_DIR} -e VENDOR_DIR=${VENDOR_DIR} -e BUILD_DIR=${BUILD_DIR} -e SOURCE_DIR=${SOURCE_DIR} -e STYLE=${STYLE} -e COVERAGE=${COVERAGE} -e WERROR=${WERROR} -e DRACO_C4=${DRACO_C4} -e AUTODOC=${AUTODOC} -e CI=${CI} -e TRAVIS=${TRAVIS} -e TRAVIS_BRANCH=${TRAVIS_BRANCH} -e CI_MERGE_REQUEST_TARGET_BRANCH_NAME=${CI_MERGE_REQUEST_TARGET_BRANCH_NAME} kinetictheory/draco-ci-2020nov:${DOCKER_TAG} /bin/bash -l -c "${SOURCE_DIR}/tools/travis-run-tests.sh"

#--------------------------------------------------------------------------------------------------#
# See also:
# - Advanced used: https://github.com/laristra/flecsi/blob/master/.travis.yml
#--------------------------------------------------------------------------------------------------#
