---
###########################
###########################
## Linter GitHub Actions ##
## github.com/github/super-linter
###########################
###########################
name: Lint Code Base

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  pull_request:
  push:
    branches-ignore:
      - 'master'
      - 'develop'

env:
  PYTHONPATH: /home/runner/work/Draco/Draco/config

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: docker://github/super-linter:v3.8.3
        env:
          DEFAULT_BRANCH: develop
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_BASH: true
          VALIDATE_DOCKERFILE: true
          VALIDATE_ENV: true
          VALIDATE_HTML: true
          VALIDATE_JSON: true
          VALIDATE_LATEX: true
          VALIDATE_LUA: true
          VALIDATE_PERL: true
          VALIDATE_PYTHON: true
          VALIDATE_RUBY: true
          VALIDATE_XML: true
          VALIDATE_YAML: true
...
